title: How well does the training work?
questions:
  - id: q1
    type: rating
    prompt: "Can you tell which files are used for training?"
    steps: 5
    low_label: "No / maybe with too much work"
    high_label: "Easily"
  - id: q1.5
    type: rating
    prompt: "How easy is it to get an overview over the training configuration before running it?"
    steps: 5
    low_label: "Impossible / maybe ok with too much work"
    high_label: "Easily"
  - id: q2
    type: rating
    prompt: "Can you tell where data preparations and augemntations happen?"
    steps: 5
    low_label: "No / maybe with too much work"
    high_label: "Easily"
  - id: q3
    type: rating
    prompt: "Can you tell where the output is written?"
    steps: 5
    low_label: "No / maybe with too much work"
    high_label: "Easily"
  - id: q4
    type: rating
    prompt: "Can you tell what loss is used?"
    steps: 5
    low_label: "No / maybe with too much work"
    high_label: "Easily"
  - id: q5
    type: rating
    prompt: "Can you tell what metric decides the best checkpoint?"
    steps: 5
    low_label: "No / maybe with too much work"
    high_label: "Easily"
  - id: q6
    type: rating
    prompt: "Did any error message tell you what to fix?"
    steps: 5
    low_label: "No / maybe with too much work"
    high_label: "Easily"
  - id: q7
    type: rating
    prompt: "How hard is it to run training?"
    steps: 5
    low_label: "Easy"
    high_label: "Hard / time consuming"
  - id: q8
    type: rating
    prompt: "How hard is it to rerun the same training twice?"
    steps: 5
    low_label: "Easy"
    high_label: "Hard / time consuming"
  - id: q9
    type: rating
    prompt: "How hard is it to understand what a model has been trained with after it was trained?"
    steps: 5
    low_label: "Easy"
    high_label: "Hard / time consuming"
  - id: q10
    type: rating
    prompt: "It the code fragile?"
    steps: 5
    low_label: "No, I know beforehand if it's going to break"
    high_label: "Yes, feel a bit random if it will work or not"

